import type {
  AdminCategory,
  AdminProduct,
  AdminRestaurant,
  ProductAllergens,
} from "./types";

export const MOCK_RESTAURANTS: AdminRestaurant[] = [
  { id: "rest_1", name: "Burger House", slug: "burger-house" },
  { id: "rest_2", name: "Sushi Master", slug: "sushi-master" },
  { id: "rest_3", name: "Pizza Roma", slug: "pizza-roma" },
  { id: "rest_4", name: "Khinkali Corner", slug: "khinkali-corner" },
];

export const MOCK_CATEGORIES: AdminCategory[] = [
  { id: "cat_1", restaurantId: "rest_1", name: "ბურგერები", sortOrder: 1 },
  { id: "cat_2", restaurantId: "rest_1", name: "სალათები", sortOrder: 2 },
  { id: "cat_3", restaurantId: "rest_1", name: "სასმელები", sortOrder: 3 },
  { id: "cat_4", restaurantId: "rest_2", name: "როლები", sortOrder: 1 },
  { id: "cat_5", restaurantId: "rest_2", name: "სეტები", sortOrder: 2 },
  { id: "cat_6", restaurantId: "rest_3", name: "პიცა", sortOrder: 1 },
  { id: "cat_7", restaurantId: "rest_3", name: "პასტა", sortOrder: 2 },
  { id: "cat_8", restaurantId: "rest_4", name: "ხინკალი", sortOrder: 1 },
  { id: "cat_9", restaurantId: "rest_4", name: "ხაჭაპური", sortOrder: 2 },
];

const allergens = (
  partial: Partial<ProductAllergens> = {},
): ProductAllergens => ({
  gluten: false,
  milk: false,
  eggs: false,
  fish: false,
  nuts: false,
  soy: false,
  vegan: false,
  vegetarian: false,
  ...partial,
});

function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const MOCK_PRODUCTS: AdminProduct[] = [
  {
    id: "prod_1",
    restaurantId: "rest_1",
    categoryId: "cat_1",
    name: "Classic Cheeseburger",
    description: "200გ საქონლის ბურგერი, ჩიზი, სალათი, სოუსი",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&h=200&fit=crop",
    gallery: [],
    price: 18.5,
    discountPrice: 15.9,
    calories: 650,
    preparationTime: 15,
    weight: 200,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ gluten: true, milk: true, eggs: true }),
    variants: [
      { id: "v1", name: "M", price: 18.5 },
      { id: "v2", name: "L", price: 24.5 },
      { id: "v3", name: "XL", price: 29.9 },
    ],
    addOns: [
      { id: "a1", name: "ბეკონი", price: 3 },
      { id: "a2", name: "ჩიზი", price: 2 },
    ],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "prod_2",
    restaurantId: "rest_1",
    categoryId: "cat_1",
    name: "Spicy Chicken Burger",
    description: "ცხარე ქათმის ფილე, კომბო სოუსი",
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=200&h=200&fit=crop",
    gallery: [],
    price: 16.9,
    discountPrice: null,
    calories: 520,
    preparationTime: 12,
    weight: 180,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ gluten: true, eggs: true }),
    variants: [],
    addOns: [{ id: "a3", name: "ჯalapeño", price: 1.5 }],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "prod_3",
    restaurantId: "rest_1",
    categoryId: "cat_2",
    name: "Caesar Salad",
    description: "რომaine, პარმეზანი, croutons, caesar სოუსი",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=200&h=200&fit=crop",
    gallery: [],
    price: 14.0,
    discountPrice: null,
    calories: 320,
    preparationTime: 8,
    weight: 250,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ gluten: true, milk: true, eggs: true, vegetarian: true }),
    variants: [],
    addOns: [{ id: "a4", name: "ქათმის ფილე", price: 5 }],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },
  {
    id: "prod_4",
    restaurantId: "rest_2",
    categoryId: "cat_4",
    name: "Salmon Roll",
    description: "8 ცალი, ორაგული, ავოკადო, კრემ-ჩიზი",
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=200&h=200&fit=crop",
    gallery: [],
    price: 22.0,
    discountPrice: 19.5,
    calories: 280,
    preparationTime: 20,
    weight: 180,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ fish: true, milk: true, soy: true }),
    variants: [
      { id: "v3", name: "M", price: 22.0 },
      { id: "v4", name: "L", price: 38.0 },
    ],
    addOns: [],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: "prod_5",
    restaurantId: "rest_2",
    categoryId: "cat_5",
    name: "Sushi Set Deluxe",
    description: "24 ცალი, მიქსი როლები და nigiri",
    image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=200&h=200&fit=crop",
    gallery: [],
    price: 55.0,
    discountPrice: null,
    calories: 890,
    preparationTime: 30,
    weight: 450,
    availability: "OUT_OF_STOCK",
    isAvailable: false,
    allergens: allergens({ fish: true, soy: true }),
    variants: [],
    addOns: [{ id: "a5", name: "wasabi extra", price: 1 }],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: "prod_6",
    restaurantId: "rest_3",
    categoryId: "cat_6",
    name: "Margherita Pizza",
    description: "32სმ, ტომატი, მოცარella, ბაზილიკი",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=200&h=200&fit=crop",
    gallery: [],
    price: 19.9,
    discountPrice: 17.5,
    calories: 780,
    preparationTime: 25,
    weight: 500,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ gluten: true, milk: true, vegetarian: true }),
    variants: [
      { id: "v5", name: "M", price: 19.9 },
      { id: "v6", name: "L", price: 26.9 },
      { id: "v7", name: "XL", price: 32.9 },
    ],
    addOns: [
      { id: "a6", name: "pepperoni", price: 4 },
      { id: "a7", name: "olives", price: 2 },
    ],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },
  {
    id: "prod_7",
    restaurantId: "rest_3",
    categoryId: "cat_7",
    name: "Carbonara",
    description: "სპაგეტი, ბეკონი, კრემი, პარმეზანი",
    image: "https://images.unsplash.com/photo-1612874742237-652db81f3b8?w=200&h=200&fit=crop",
    gallery: [],
    price: 17.5,
    discountPrice: null,
    calories: 620,
    preparationTime: 18,
    weight: 350,
    availability: "UNAVAILABLE",
    isAvailable: false,
    allergens: allergens({ gluten: true, milk: true, eggs: true }),
    variants: [],
    addOns: [],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(12),
  },
  {
    id: "prod_8",
    restaurantId: "rest_4",
    categoryId: "cat_8",
    name: "ხინკალი (10 ცალი)",
    description: "ქართული ტრადიციული ხინკალი",
    image: "https://images.unsplash.com/photo-1603133872875-68410337964?w=200&h=200&fit=crop",
    gallery: [],
    price: 12.0,
    discountPrice: null,
    calories: 450,
    preparationTime: 20,
    weight: 400,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ gluten: true }),
    variants: [
      { id: "v8", name: "S", price: 7 },
      { id: "v9", name: "M", price: 12.0 },
      { id: "v10", name: "L", price: 16 },
    ],
    addOns: [{ id: "a8", name: "სულგუნი", price: 3 }],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "prod_9",
    restaurantId: "rest_4",
    categoryId: "cat_9",
    name: "Adjarian Khachapuri",
    description: "Adjaruli style, კვერცხი, კარაქი",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=200&h=200&fit=crop",
    gallery: [],
    price: 13.5,
    discountPrice: null,
    calories: 720,
    preparationTime: 22,
    weight: 380,
    availability: "HIDDEN",
    isAvailable: false,
    allergens: allergens({ gluten: true, milk: true, eggs: true, vegetarian: true }),
    variants: [],
    addOns: [],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(25),
  },
  {
    id: "prod_10",
    restaurantId: "rest_1",
    categoryId: "cat_3",
    name: "Fresh Lemonade",
    description: "500ml, ნatural lemonade",
    image: "https://images.unsplash.com/photo-1523672063438-91d6883381c6?w=200&h=200&fit=crop",
    gallery: [],
    price: 5.5,
    discountPrice: null,
    calories: 120,
    preparationTime: 3,
    weight: 500,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ vegan: true, vegetarian: true }),
    variants: [
      { id: "v11", name: "M", price: 5.5 },
      { id: "v12", name: "L", price: 9.0 },
    ],
    addOns: [],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(6),
  },
  {
    id: "prod_11",
    restaurantId: "rest_2",
    categoryId: "cat_4",
    name: "Tuna Roll",
    description: "8 ცალი, tuna, cucumber",
    image: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=200&h=200&fit=crop",
    gallery: [],
    price: 18.0,
    discountPrice: 16.0,
    calories: 240,
    preparationTime: 15,
    weight: 160,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ fish: true, soy: true }),
    variants: [],
    addOns: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },
  {
    id: "prod_12",
    restaurantId: "rest_3",
    categoryId: "cat_6",
    name: "Pepperoni Pizza",
    description: "32სმ, pepperoni, cheese",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=200&h=200&fit=crop",
    gallery: [],
    price: 21.9,
    discountPrice: null,
    calories: 850,
    preparationTime: 25,
    weight: 520,
    availability: "AVAILABLE",
    isAvailable: true,
    allergens: allergens({ gluten: true, milk: true }),
    variants: [],
    addOns: [{ id: "a9", name: "extra cheese", price: 3 }],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
];

export function getRestaurantName(id: string, restaurants = MOCK_RESTAURANTS) {
  return restaurants.find((r) => r.id === id)?.name ?? "—";
}

export function getCategoryName(id: string, categories = MOCK_CATEGORIES) {
  return categories.find((c) => c.id === id)?.name ?? "—";
}

export function getCategoriesForRestaurant(
  restaurantId: string,
  categories = MOCK_CATEGORIES,
) {
  if (!restaurantId) return categories;
  return categories.filter((c) => c.restaurantId === restaurantId);
}
