import type { AdminRestaurant, WorkingHourEntry } from "./types";

const defaultHours = (): WorkingHourEntry[] => [
  { day: "monday", openTime: "10:00", closeTime: "22:00", isClosed: false },
  { day: "tuesday", openTime: "10:00", closeTime: "22:00", isClosed: false },
  { day: "wednesday", openTime: "10:00", closeTime: "22:00", isClosed: false },
  { day: "thursday", openTime: "10:00", closeTime: "22:00", isClosed: false },
  { day: "friday", openTime: "10:00", closeTime: "23:00", isClosed: false },
  { day: "saturday", openTime: "11:00", closeTime: "23:00", isClosed: false },
  { day: "sunday", openTime: "11:00", closeTime: "21:00", isClosed: false },
];

function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const MOCK_RESTAURANTS: AdminRestaurant[] = [
  {
    id: "rest_1",
    name: "Burger House",
    slug: "burger-house",
    description: "პრემიუმ ბურგერები და კარტოფილი ფრი.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u1",
      firstName: "გიორგი",
      lastName: "ბერიძე",
      email: "giorgi@burgerhouse.ge",
      phone: "+995555123456",
    },
    country: "საქართველო",
    city: "თბილისი",
    address: "Rustaveli Ave 12",
    latitude: 41.7151,
    longitude: 44.8271,
    categories: ["ბურგერი", "კაფე"],
    deliveryRadius: 5,
    deliveryFee: 3.5,
    minimumOrder: 15,
    estimatedDeliveryMinutes: 35,
    phone: "+995322123456",
    email: "info@burgerhouse.ge",
    website: "https://burgerhouse.ge",
    rating: 4.7,
    reviewCount: 128,
    isOpen: true,
    isSuspended: false,
    approvalStatus: "approved",
    totalProducts: 24,
    totalOrders: 842,
    revenue: 28450,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: true,
      featured: true,
      visible: true,
      approved: true,
    },
    reviews: [
      {
        id: "r1",
        authorName: "ნინო კ.",
        rating: 5,
        comment: "საუკეთესო ბურგერი ქალაქში!",
        createdAt: daysAgo(2),
      },
    ],
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: "rest_2",
    name: "Sushi Master",
    slug: "sushi-master",
    description: "ავთენტური იაპონური სუში.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u2",
      firstName: "ანა",
      lastName: "მელაძე",
      email: "ana@sushi.ge",
      phone: "+995555234567",
    },
    country: "საქართველო",
    city: "თბილისი",
    address: "ჭავჭავაძის გამზ. 45",
    latitude: 41.7089,
    longitude: 44.7478,
    categories: ["სუში", "აზიური"],
    deliveryRadius: 4,
    deliveryFee: 4,
    minimumOrder: 25,
    estimatedDeliveryMinutes: 40,
    phone: "+995322234567",
    email: "hello@sushi.ge",
    website: null,
    rating: 4.9,
    reviewCount: 256,
    isOpen: true,
    isSuspended: false,
    approvalStatus: "approved",
    totalProducts: 38,
    totalOrders: 1204,
    revenue: 52100,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: true,
      featured: true,
      visible: true,
      approved: true,
    },
    reviews: [],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
  },
  {
    id: "rest_3",
    name: "Pizza Roma",
    slug: "pizza-roma",
    description: "იტალიური პიცა ხის ღუმით.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u3",
      firstName: "Luka",
      lastName: "როსი",
      email: "luka@pizzaroma.ge",
      phone: "+995555345678",
    },
    country: "საქართველო",
    city: "ბათუმი",
    address: "გორგილაძის 8",
    latitude: 41.6461,
    longitude: 41.6337,
    categories: ["პიცა", "იტალიური"],
    deliveryRadius: 6,
    deliveryFee: 2.5,
    minimumOrder: 20,
    estimatedDeliveryMinutes: 30,
    phone: "+995422345678",
    email: null,
    website: "https://pizzaroma.ge",
    rating: 4.5,
    reviewCount: 89,
    isOpen: false,
    isSuspended: false,
    approvalStatus: "approved",
    totalProducts: 18,
    totalOrders: 456,
    revenue: 15200,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: false,
      featured: false,
      visible: true,
      approved: true,
    },
    reviews: [],
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },
  {
    id: "rest_4",
    name: "Khinkali Corner",
    slug: "khinkali-corner",
    description: "ტრადიციული ქართული ხინკალი.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u4",
      firstName: "Mariam",
      lastName: "გელაშვილი",
      email: "mariam@khinkali.ge",
      phone: "+995555456789",
    },
    country: "საქართველო",
    city: "თბილისი",
    address: "აღმაშენებლის 102",
    latitude: 41.6938,
    longitude: 44.8015,
    categories: ["ქართული"],
    deliveryRadius: 5,
    deliveryFee: 3,
    minimumOrder: 12,
    estimatedDeliveryMinutes: 25,
    phone: "+995322456789",
    email: "info@khinkali.ge",
    website: null,
    rating: 4.8,
    reviewCount: 312,
    isOpen: true,
    isSuspended: false,
    approvalStatus: "approved",
    totalProducts: 15,
    totalOrders: 2100,
    revenue: 67800,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: true,
      featured: true,
      visible: true,
      approved: true,
    },
    reviews: [],
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "rest_5",
    name: "Green Bowl",
    slug: "green-bowl",
    description: "ჯანსაღი სალათები და სმუზები.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u5",
      firstName: "Elene",
      lastName: "Kvaratskhelia",
      email: "elene@greenbowl.ge",
      phone: "+995555567890",
    },
    country: "საქართველო",
    city: "ქუთაისი",
    address: "თამარ მეფის 5",
    latitude: 42.2679,
    longitude: 42.6946,
    categories: ["სალათები", "კაფე"],
    deliveryRadius: 4,
    deliveryFee: 2,
    minimumOrder: 10,
    estimatedDeliveryMinutes: 20,
    phone: "+995431567890",
    email: "hello@greenbowl.ge",
    website: null,
    rating: 4.3,
    reviewCount: 45,
    isOpen: true,
    isSuspended: false,
    approvalStatus: "pending",
    totalProducts: 0,
    totalOrders: 0,
    revenue: 0,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: true,
      featured: false,
      visible: false,
      approved: false,
    },
    reviews: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "rest_6",
    name: "Taco Fiesta",
    slug: "taco-fiesta",
    description: "მექსიკური სამზარეულო.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u6",
      firstName: "David",
      lastName: "ონიანი",
      email: "david@taco.ge",
      phone: "+995555678901",
    },
    country: "საქართველო",
    city: "რუსთავი",
    address: "Kostava 21",
    latitude: 41.5493,
    longitude: 44.9932,
    categories: ["ბურგერი", "აზიური"],
    deliveryRadius: 3,
    deliveryFee: 3.5,
    minimumOrder: 18,
    estimatedDeliveryMinutes: 35,
    phone: "+995341678901",
    email: null,
    website: null,
    rating: 0,
    reviewCount: 0,
    isOpen: false,
    isSuspended: false,
    approvalStatus: "pending",
    totalProducts: 0,
    totalOrders: 0,
    revenue: 0,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: false,
      featured: false,
      visible: false,
      approved: false,
    },
    reviews: [],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "rest_7",
    name: "Sweet Dreams",
    slug: "sweet-dreams",
    description: "დესერტები და tortebi.",
    logo: null,
    coverImage: null,
    owner: {
      id: "u7",
      firstName: "Sofio",
      lastName: "Abashidze",
      email: "sofio@sweet.ge",
      phone: "+995555789012",
    },
    country: "საქართველო",
    city: "თბილისი",
    address: "Vazha-Pshavela 34",
    latitude: 41.7211,
    longitude: 44.7367,
    categories: ["დესერტი", "კაფე"],
    deliveryRadius: 5,
    deliveryFee: 2.5,
    minimumOrder: 8,
    estimatedDeliveryMinutes: 25,
    phone: "+995322789012",
    email: "orders@sweet.ge",
    website: "https://sweet.ge",
    rating: 4.6,
    reviewCount: 67,
    isOpen: true,
    isSuspended: true,
    approvalStatus: "approved",
    totalProducts: 22,
    totalOrders: 189,
    revenue: 4200,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: false,
      featured: false,
      visible: true,
      approved: true,
    },
    reviews: [],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(7),
  },
  {
    id: "rest_8",
    name: "Kebab King",
    slug: "kebab-king",
    description: null,
    logo: null,
    coverImage: null,
    owner: {
      id: "u8",
      firstName: "Ramin",
      lastName: "Həsənov",
      email: "ramin@kebab.ge",
      phone: "+995555890123",
    },
    country: "საქართველო",
    city: "ბათუმი",
    address: "Sherif Khimshiashvili 1",
    latitude: 41.6389,
    longitude: 41.6358,
    categories: ["აზიური"],
    deliveryRadius: 4,
    deliveryFee: 3,
    minimumOrder: 15,
    estimatedDeliveryMinutes: 30,
    phone: "+995422890123",
    email: null,
    website: null,
    rating: 3.2,
    reviewCount: 12,
    isOpen: false,
    isSuspended: false,
    approvalStatus: "rejected",
    totalProducts: 0,
    totalOrders: 0,
    revenue: 0,
    workingHours: defaultHours(),
    settings: {
      acceptingOrders: false,
      featured: false,
      visible: false,
      approved: false,
    },
    reviews: [],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(10),
  },
];

export function getRestaurantById(id: string): AdminRestaurant | undefined {
  return MOCK_RESTAURANTS.find((r) => r.id === id);
}
