import type { OrderStatus } from "@/lib/types";

export const ORDER_STATUS_LABELS: Record<OrderStatus | string, string> = {
  PENDING: "მოლოდინში",
  ACCEPTED: "მიღებული",
  PREPARING: "მზადდება",
  READY: "მზადაა",
  PICKED_UP: "აღებულია",
  ON_THE_WAY: "გზაშია",
  DELIVERED: "მიწოდებული",
  CANCELLED: "გაუქმებული",
};

export const PAYMENT_STATUS_LABELS: Record<string, string> = {
  PENDING: "მოლოდინში",
  PAID: "გადახდილი",
  FAILED: "ჩავარდა",
  REFUNDED: "დაბრუნებული",
};

export const PAYMENT_METHOD_LABELS: Record<string, string> = {
  CARD: "ბარათი",
  CASH: "ნაღდი",
  APPLE_PAY: "Apple Pay",
  GOOGLE_PAY: "Google Pay",
};

export const PRODUCT_AVAILABILITY_LABELS: Record<string, string> = {
  AVAILABLE: "ხელმისაწვდომი",
  UNAVAILABLE: "არ არის ხელმისაწვდომი",
  HIDDEN: "დამალული",
  OUT_OF_STOCK: "ამოწურული",
};

export const DAY_LABELS: Record<string, string> = {
  MONDAY: "ორშაბათი",
  TUESDAY: "სამშაბათი",
  WEDNESDAY: "ოთხშაბათი",
  THURSDAY: "ხუთშაბათი",
  FRIDAY: "პარასკევი",
  SATURDAY: "შაბათი",
  SUNDAY: "კვირა",
};

export const NAV_ITEMS = [
  { href: "/restaurant/dashboard", label: "მთავარი", icon: "LayoutDashboard" },
  { href: "/restaurant/orders", label: "შეკვეთები", icon: "ShoppingBag" },
  { href: "/restaurant/menu", label: "მენიუ", icon: "UtensilsCrossed" },
  { href: "/restaurant/products", label: "პროდუქტები", icon: "Package" },
  { href: "/restaurant/categories", label: "კატეგორიები", icon: "Layers" },
  { href: "/restaurant/reviews", label: "მიმოხილვები", icon: "Star" },
  { href: "/restaurant/analytics", label: "ანალიტიკა", icon: "BarChart3" },
  { href: "/restaurant/settings", label: "პარამეტრები", icon: "Settings" },
  { href: "/restaurant/profile", label: "პროფილი", icon: "User" },
] as const;

export const ORDER_ACTION_STATUS: Record<string, string> = {
  accept: "ACCEPTED",
  reject: "CANCELLED",
  preparing: "PREPARING",
  ready: "READY",
  completed: "PICKED_UP",
};

/** UI strings — Georgian */
export const KA = {
  ownerPanel: "მფლობელის პანელი",
  restaurant: "რესტორანი",
  owner: "მფლობელი",
  collapse: "ჩაკეცვა",
  backToStore: "საიტზე დაბრუნება",
  myAccount: "ჩემი ანგარიში",
  profileNav: "პროფილი",
  restaurantSettings: "რესტორნის პარამეტრები",
  searchPlaceholder: "შეკვეთები, პროდუქტები...",
  loading: "იტვირთება...",
  saved: "შენახულია!",
  saveChanges: "შენახვა",
  cancel: "გაუქმება",
  confirm: "დადასტურება",
  delete: "წაშლა",
  create: "შექმნა",
  edit: "რედაქტირება",
  duplicate: "დუბლირება",
  viewAll: "ყველას ნახვა",
  viewDetails: "დეტალები",
  image: "სურათი",
  noImage: "სურათი არ არის",
  hidden: "დამალული",
  visible: "ხილული",
  open: "ღია",
  closed: "დაკეტილი",
  optional: "არასავალდებულო",
  sale: "აქცია",
  allStatuses: "ყველა სტატუსი",
  allPayments: "ყველა გადახდა",
  status: "სტატუსი",
  payment: "გადახდა",
  method: "მეთოდი",
  date: "თარიღი",
  actions: "მოქმედებები",
  customer: "მომხმარებელი",
  items: "ნივთები",
  total: "ჯამი",
  order: "შეკვეთა",
  notes: "შენიშვნები",
  deliveryAddress: "მიწოდების მისამართი",
  orderItems: "შეკვეთის ნივთები",
  accept: "მიღება",
  reject: "გაუქმება",
  markPreparing: "მზადდება",
  markReady: "მზადაა",
  markPickedUp: "აღებულია",
  restaurantNotFound: "რესტორანი ვერ მოიძებნა",
  restaurantNotFoundDesc:
    "თქვენს ანგარიშს რესტორანი არ არის მიბმული. შექმენით რესტორანი ქვემოთ მოცემული ფორმით.",
  onboarding: {
    title: "რესტორანის შექმნა",
    subtitle:
      "შეავსეთ ძირითადი ინფორმაცია. საიტზე გამოჩენა მოხდება ადმინისტრატორის დამტკიცების შემდეგ.",
    createRestaurant: "რესტორანის შექმნა",
    creating: "იქმნება...",
    success: "რესტორანი წარმატებით შეიქმნა!",
    pendingApproval:
      "რესტორანი ჯერ არ არის დამტკიცებული და საჯარო სიაში არ ჩანს. დაელოდეთ ადმინისტრატორის დამტკიცებას.",
    pendingApprovalTitle: "ადმინისტრატორის დამტკიცება საჭიროა",
    categories: "კატეგორიები",
    selectCategories: "აირჩიეთ კატეგორიები",
    street: "ქუჩა",
    slug: "Slug (URL)",
    slugHint: "ცარიელი დატოვეთ — ავტომატურად შეიქმნება",
    logo: "ლოგო",
    coverImage: "საფარის ფოტო",
  },
  failedLoad: "მონაცემების ჩატვირთვა ვერ მოხერხდა",
  failedSave: "შენახვა ვერ მოხერხდა",
  failedDelete: "წაშლა ვერ მოხერხდა",
  passwordsMismatch: "პაროლები არ ემთხვევა",
  enterCurrentPassword: "პაროლის შესაცვლელად შეიყვანეთ მიმდინარე პაროლი",
  leavePasswordBlank: "დატოვეთ ცარიელი, თუ არ ცვლით",
  chartPlaceholder: "გრაფიკის ადგილი — დააკავშირეთ ანალიტიკა",
  noDataYet: "მონაცემები ჯერ არ არის",
  justNow: "ახლახან",
  minutesAgo: "წუთის წინ",
  hoursAgo: "საათის წინ",
  daysAgo: "დღის წინ",
  vsYesterday: "გუშინდელთან",
  vsLastMonth: "წინა თვესთან",
  vsLastWeek: "წინა კვირასთან",
  dashboard: {
    title: "მთავარი",
    welcome: "კეთილი იყოს თქვენი მობრძანება!",
    subtitle: "აქ არის დღევანდელი სიახლეები.",
    todayOrders: "დღევანდელი შეკვეთები",
    pendingOrders: "მოლოდინში",
    preparing: "მზადდება",
    ready: "მზადაა",
    completedToday: "დღეს დასრულებული",
    todayRevenue: "დღევანდელი შემოსავალი",
    monthlyRevenue: "თვის შემოსავალი",
    averageRating: "საშუალო რეიტინგი",
    revenueOverview: "შემოსავლის მიმოხილვა",
    revenueOverviewDesc: "ბოლო 30 დღის შემოსავალი",
    recentOrders: "ბოლო შეკვეთები",
    latestReviews: "ბოლო მიმოხილვები",
    popularProducts: "პოპულარული პროდუქტები",
  },
  orders: {
    title: "შეკვეთები",
    subtitle: "მართეთ შემოსული შეკვეთები და განაახლეთ სტატუსი.",
    search: "შეკვეთების ძებნა...",
    empty: "შეკვეთები ვერ მოიძებნა",
    emptyDesc: "სცადეთ ფილტრების შეცვლა ან შეამოწმეთ მოგვიანებით.",
  },
  menu: {
    title: "მენიუ",
    subtitle: "ფიქსირებული კატეგორიები. დაამატეთ საჭმელი ნებისმიერ სექციაში.",
    createCategory: "კატეგორიის შექმნა",
    editCategory: "კატეგორიის რედაქტირება",
    empty: "მენიუს კატეგორიები არ არის",
    emptyDesc: "განაახლეთ გვერდი — კატეგორიები ავტომატურად იქმნება.",
    deleteTitle: "კატეგორიის წაშლა",
    deleteDesc:
      "დარწმუნებული ხართ, რომ გსურთ „{name}“ წაშლა? კატეგორიის პროდუქტები უნდა გადაიტანოთ ან წაშალოთ.",
    show: "ჩვენება",
    hide: "დამალვა",
    productsCount: "პროდუქტი",
    addProduct: "საჭმლის დამატება",
    addCombo: "კომბოს დამატება",
    noProducts: "ამ კატეგორიაში პროდუქტები არ არის",
    noProductsDesc: "დაამატეთ პირველი საჭმელი ამ კატეგორიაში.",
    deleteCategoryBlocked:
      "„{name}“ შეიცავს {count} პროდუქტს. ჯერ წაშალეთ ან გადაიტანეთ ისინი.",
  },
  products: {
    title: "პროდუქტები",
    subtitle: "მართეთ რესტორნის პროდუქტების კატალოგი.",
    create: "პროდუქტის შექმნა",
    createCombo: "კომბო მენიუს შექმნა",
    edit: "პროდუქტის რედაქტირება",
    editCombo: "კომბო მენიუს რედაქტირება",
    search: "პროდუქტების ძებნა...",
    empty: "პროდუქტები ვერ მოიძებნა",
    emptyNoCategory: "კატეგორიები ავტომატურად იქმნება. განაახლეთ გვერდი.",
    emptySearch: "შექმენით პირველი პროდუქტი ან შეცვალეთ ძებნა.",
    deleteTitle: "პროდუქტის წაშლა",
    deleteDesc: "დარწმუნებული ხართ, რომ გსურთ „{name}“ წაშლა?",
    selectCategory: "აირჩიეთ კატეგორია",
    prepTime: "მომზადების დრო (წთ)",
    discountPrice: "ფასდაკლება",
    price: "ფასი",
    availability: "ხელმისაწვდომობა",
    imageUrl: "სურათის URL",
    description: "აღწერა",
    name: "სახელი",
    category: "კატეგორია",
    productKind: "ტიპი",
    productKindItem: "კერძი",
    productKindCombo: "კომბო მენიუ",
    comboHint:
      "კომბოს აქვს საკუთარი სურათი და ფიქსირებული ფასი. ვარიანტები არ გამოიყენება.",
    variants: "ზომები (არასავალდებულო)",
    variantsEmpty:
      "ზომები არ არის მითითებული — სურვილისამებრ შეიყვანეთ ფასი S, M, L, XL ან XXL ზომებისთვის",
    customizationGroups: "ოფციები",
    customizationGroupsHint:
      "დაწერე ოფციის სახელი და ვარიანტები მძიმით — მაგ. კეტჩუპი, მაიონეზი, ყველი +2",
    exclusions: "გამონაკლისები",
    exclusionsHint:
      "რა არ უნდა იყოს კერძში — მომხმარებელი აირჩევს სურვილისამებრ",
  },
  categories: {
    title: "პროდუქტის კატეგორიები",
    subtitle: "კატეგორიები ფიქსირებულია. საჭმელი დაამატეთ მენიუდან.",
    create: "კატეგორიის შექმნა",
    edit: "კატეგორიის რედაქტირება",
    empty: "კატეგორიები ჯერ არ არის",
    emptyDesc: "კატეგორიები ფიქსირებულია და ავტომატურად იქმნება.",
    deleteTitle: "კატეგორიის წაშლა",
    deleteDesc: "დარწმუნებული ხართ, რომ გსურთ „{name}“ წაშლა?",
    sortOrder: "დალაგება",
  },
  reviews: {
    title: "მიმოხილვები",
    subtitle: "წაიკითხეთ მომხმარებელთა გამოხმაურება.",
    empty: "მიმოხილვები ჯერ არ არის",
    emptyDesc: "მიმოხილვები გამოჩნდება შეკვეთის დასრულების შემდეგ.",
    deleteTitle: "მიმოხილვის წაშლა",
    deleteDesc: "დარწმუნებული ხართ, რომ გსურთ ამ მიმოხილვის წაშლა?",
  },
  analytics: {
    title: "ანალიტიკა",
    subtitle: "თვალყური ადევნეთ შემოსავალს და შეკვეთებს.",
    monthlyRevenue: "თვის შემოსავალი",
    weekOrders: "კვირის შეკვეთები",
    avgOrderValue: "საშ. შეკვეთის ღირ.",
    revenue: "შემოსავალი",
    revenueDesc: "თვიური შემოსავლის მიმდინარეობა",
    orders: "შეკვეთები",
    ordersDesc: "კვირის შეკვეთები დღეების მიხედვით",
    bestSellers: "ბესტსელერები",
    popularCategories: "პოპულარული კატეგორიები",
  },
  settings: {
    title: "რესტორნის პარამეტრები",
    subtitle: "მართეთ რესტორნის პროფილი და სამუშაო საათები.",
    general: "ზოგადი",
    hours: "სამუშაო საათები",
    generalInfo: "ზოგადი ინფორმაცია",
    logo: "ლოგო",
    coverImage: "საფარის ფოტო",
    restaurantName: "რესტორნის სახელი",
    phone: "ტელეფონი",
    email: "ელფოსტა",
    address: "მისამართი",
    city: "ქალაქი",
    mapLocation: "მდებარეობა რუკაზე",
    mapLocationDesc: "დააწკაპუნეთ რუკაზე ან გამოიყენეთ „ჩემი მდებარეობა“",
    acceptingOrders: "შეკვეთების მიღება",
    acceptingOrdersDesc: "რესტორანი ღიაა თუ დაკეტილი",
    workingHours: "სამუშაო საათები",
    noWorkingHours: "სამუშაო საათები არ არის მითითებული",
  },
  profile: {
    title: "პროფილი",
    subtitle: "მართეთ პირადი ანგარიშის ინფორმაცია.",
    avatar: "ავატარი",
    avatarPhoto: "ფოტო",
    personalInfo: "პირადი ინფორმაცია",
    firstName: "სახელი",
    lastName: "გვარი",
    address: "მისამართი",
    street: "ქუჩა",
    building: "სახლი/№",
    apartment: "ბინა",
    pickOnMap: "აირჩიე რუკაზე",
    changePassword: "პაროლის შეცვლა",
    currentPassword: "მიმდინარე პაროლი",
    newPassword: "ახალი პაროლი",
    confirmPassword: "პაროლის დადასტურება",
  },
} as const;

/** Translate common API error messages to Georgian */
export function translateApiError(message: string): string {
  const map: Record<string, string> = {
    "Restaurant not found": KA.restaurantNotFound,
    "რესტორანი ვერ მოიძებნა": KA.restaurantNotFound,
    "თქვენს ანგარიშს უკვე აქვს რესტორანი": "თქვენს ანგარიშს უკვე აქვს რესტორანი",
    "slug უკვე გამოყენებულია": "ეს slug უკვე გამოყენებულია",
    "Category not found": "კატეგორია ვერ მოიძებნა",
    "Product not found": "პროდუქტი ვერ მოიძებნა",
    "Order not found": "შეკვეთა ვერ მოიძებნა",
    "Review not found": "მიმოხილვა ვერ მოიძებნა",
    Unauthorized: "სესია ამოიწურა. თავიდან შედი ანგარიშში.",
    "Request failed": KA.failedLoad,
  };
  return map[message] ?? message;
}
